spring:
  application:
    name: springboot-cicd-poc

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  server:
    port: 8081
